# Generated by Django 5.0.6 on 2024-06-27 10:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('gasoline', 'Gasoline'), ('diesel', 'Diesel'), ('biodiesel', 'Biodiesel'), ('ethanol', 'Ethanol'), ('cng', 'CNG'), ('lpg', 'LPG'), ('hydrogen', 'Hydrogen')], max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('cvt', 'CVT'), ('semi-automatic', 'Semi-Automatic')], max_length=50),
        ),
        migrations.AlterField(
            model_name='marka',
            name='age_of_issue',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(2050)]),
        ),
        migrations.AlterField(
            model_name='marka',
            name='style',
            field=models.CharField(choices=[('sedan', 'Sedan'), ('hatchback', 'HatchBack'), ('liftback', 'Liftback'), ('coupe', 'Coupe'), ('crossover', 'Crossover'), ('truck', 'Truck'), ('wagon', 'Wagon')], max_length=100),
        ),
    ]
